"""empty message

Revision ID: c4c50425399b
Revises: 4f538a021b91
Create Date: 2022-03-22 13:03:16.745396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4c50425399b'
down_revision = '4f538a021b91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Property_location_key', 'Property', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('Property_location_key', 'Property', ['location'])
    # ### end Alembic commands ###
